### Numpy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

### Create a NumPy ndarray Object

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Array Indexing

In [3]:
print(arr[0])

print(arr[2] + arr[3])

1
7


### numpy.eye() function
The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.


In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Creating Multi-Dimensional Arrays in NumPy

In [7]:
# Create a 2D array (3x3 matrix)
matrix_a = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]])

print(matrix_a)

matrix_b = np.array([[9, 8, 7], 
                     [6, 5, 4], 
                     [3, 2, 1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Element-wise multiplication

In [9]:

element_wise_product = matrix_a * matrix_b
print("Element-wise multiplication:\n", element_wise_product)


Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


### Higher-Dimensional Arrays

In [10]:
# Create a 3D array (2x2x2)
array_3d = np.array([[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]])

print(array_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Multiplication in Higher Dimensions

In [11]:
# Create another 3D array
array_3d_b = np.array([[[8, 7], [6, 5]], 
                       [[4, 3], [2, 1]]])

# Element-wise multiplication
element_wise_product_3d = array_3d * array_3d_b

print("Element-wise multiplication for 3D arrays:\n", element_wise_product_3d)


Element-wise multiplication for 3D arrays:
 [[[ 8 14]
  [18 20]]

 [[20 18]
  [14  8]]]


### Matrix Multiplication for 3D Arrays

In [12]:
# Matrix multiplication for 3D arrays
matrix_product_3d = np.matmul(array_3d, array_3d_b)

print("Matrix multiplication for 3D arrays:\n", matrix_product_3d)


Matrix multiplication for 3D arrays:
 [[[20 17]
  [48 41]]

 [[32 21]
  [44 29]]]


### Reshape From 1-D to 2-D

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Splitting NumPy Arrays

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
